# Generated by Django 6.0.1 on 2026-01-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renting", "0002_alter_appuser_birth_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appuser",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
