# Generated by Django 6.0.1 on 2026-01-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renting", "0003_appuser_is_staff_appuser_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
